---
- name: Nginx Playbook
  hosts: web
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update all packages on RedHat-based systems
      yum:
        name: '*'
        state: latest
      when: ansible_facts ['distribution'] in ['Amazon', 'Redhat']
            
    - name: Update all packages on Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts ['distribution'] in ['Ubuntu', 'Debian']

    - name: Ensure Nginx is installed on RedHat-based systems
      yum:
        name: nginx
        state: present
      when: ansible_facts ['distribution'] in ['Amazon', 'Redhat']

    - name: Ensure Nginx is installed on Debian-based systems
      apt:
        name: nginx
        state: present
      when: ansible_facts ['distribution'] in ['Ubuntu', 'Debian']

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes